---
title: "Influenza A H7N9 in China, 2013"
format: dashboard
theme: lux
---

```{r}
# Load packages 
if(!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, outbreaks, bslib, bsicons, shiny, 
               rgeoboundaries, plotly, htmltools, reactable)

# view data
#head(outbreaks::fluH7N9_china_2013)
```

```{r}
Flu_china <- fluH7N9_china_2013

Total_cases <- Flu_china %>% 
  select(province) %>% 
  nrow()


total_hospi <- Flu_china %>% 
  filter(!is.na(date_of_hospitalisation)) %>% 
  nrow()



total_deaths <- Flu_china %>% 
  filter(outcome == "Death") %>% 
  nrow()


```


```{r}
### MAP OF CASES PER PROVINCE
province_summary <- fluH7N9_china_2013 %>% 
  group_by(province) %>% 
  summarise(total_cases = n()) 

china_map <- rgeoboundaries::gb_adm1("china")

# Check the keys to see if join will be successful
#setdiff(province_summary$province, china_map$shapeName)
#setdiff(china_map$shapeName, province_summary$province)
# Some work to be done to harmonize these

china_map <- china_map %>%
  # Remove the strings Province, Municipality and Autonomous Region 
  # to allow matching
  mutate(province = str_trim(
    str_remove(shapeName, "Province|Municipality|Autonomous Region")
  ))

# Check if join will work fine
#setdiff(province_summary$province, china_map$province)

# Fix Guangdong, which based on a quick Google is actually Guangzhou
china_map <- china_map %>% 
  mutate(province = if_else(province == "Guangzhou", "Guangdong", province)) 
  
# Check again
#setdiff(province_summary$province, china_map$province)

# Now join
china_map_joined <- 
  left_join(china_map, province_summary, by = "province") %>% 
  # Create tooltip label 
  mutate(tooltip_label = paste0(province, ": ", total_cases))

china_map_plot <- ggplot(china_map_joined) +
  geom_sf(aes(fill = total_cases, text = tooltip_label)) + 
  theme_void() +
  labs(fill = "Number of Cases") + 
  theme(legend.position = "none")

china_map_plot_ggplotly <- 
  ggplotly(china_map_plot, tooltip = "text")

```

```{r}
# NUMBER OF CASES BY PROVINCE

province_summary <- Flu_china %>% 
  group_by(province) %>% 
  summarise(cases_province = n()) %>% 
  mutate(cases_province = as.numeric(cases_province))
       
       
province_cases <- province_summary %>% 
  arrange(desc(cases_province)) %>% 
  mutate(tooltip_label = paste(province, 
                               cases_province, 
                               sep = ": ")) %>% 
  ggplot(aes(y = reorder(province, cases_province), 
             x = cases_province, 
             text = tooltip_label)) + 
  geom_col(fill = "steelblue") +
  labs(y = "Province", 
       x = "Number of Cases") 
 
province_cases_ggplotly <- 
  ggplotly(province_cases, tooltip = "text")
      
```


# HOME 

## Row 1 {height=25%}


```{r}
value_box(
  title = "Total Cases",
  value = Total_cases,
  showcase = bsicons::bs_icon("virus"),
  theme = value_box_theme(bg = "#518fd6")
)
```



```{r}
value_box(
  title = "Total Hospitalizations",
  value = total_hospi,
  showcase = bsicons::bs_icon("hospital"),
  theme = value_box_theme(bg = "#214773")
)

```


```{r}
value_box(
  title = "Total Deaths",
  value = total_deaths,
  showcase = bsicons::bs_icon("Clipboard2 pulse"),
  theme = value_box_theme(bg = "#3f71ab")
)

```

## Row 2 {height=75%}

### {width=30%}


```{r title = "Number Cases by Provinces"}

province_cases_ggplotly

```

### {width=70%}

```{r title = "Map of Provinces by Number of Cases"}

china_map_plot_ggplotly

```


# DOWNLOAD DATA

The data used in this dashboard is shown below and can be downloaded as a CSV.

```{r}

htmltools::browsable(
  tagList(
    reactable(Flu_china, 
              elementId = "Flu_china-table", 
              searchable = T, 
              filterable = T), 
    
tags$button("Download as CSV", 
            onclick = "Reactable.downloadDataCSV('Flu_china-table')")
  )
)

```



